-- MySQL Script generated by MySQL Workbench
-- lun. 17 oct. 2016 14:42:03 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema appCompta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appCompta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appCompta` DEFAULT CHARACTER SET utf8 ;
USE `appCompta` ;

-- -----------------------------------------------------
-- Table `appCompta`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appCompta`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `user_color` VARCHAR(45) NULL,
  `user_role` VARCHAR(45) NULL,
  `user_pwd` VARCHAR(100) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appCompta`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appCompta`.`user_group` (
  `id_user_group` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appCompta`.`users_has_user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appCompta`.`users_has_user_group` (
  `user_id` INT NOT NULL,
  `id_user_group` INT NOT NULL,
  PRIMARY KEY (`user_id`, `id_user_group`),
  INDEX `fk_users_has_user_group_user_group1_idx` (`id_user_group` ASC),
  INDEX `fk_users_has_user_group_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_user_group_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `appCompta`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_user_group_user_group1`
    FOREIGN KEY (`id_user_group`)
    REFERENCES `appCompta`.`user_group` (`id_user_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appCompta`.`depenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appCompta`.`depenses` (
  `id_depenses` INT NOT NULL AUTO_INCREMENT,
  `montant` FLOAT NULL,
  `date` DATE NULL,
  `description` VARCHAR(300) NULL,
  `id_users` INT NOT NULL,
  PRIMARY KEY (`id_depenses`),
  INDEX `fk_depenses_users1_idx` (`id_users` ASC),
  CONSTRAINT `fk_depenses_users1`
    FOREIGN KEY (`id_users`)
    REFERENCES `appCompta`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appCompta`.`concernes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appCompta`.`concernes` (
  `id_depenses` INT NOT NULL,
  `id_users` INT NOT NULL,
  PRIMARY KEY (`id_depenses`, `id_users`),
  INDEX `fk_depenses_has_users_users1_idx` (`id_users` ASC),
  INDEX `fk_depenses_has_users_depenses1_idx` (`id_depenses` ASC),
  CONSTRAINT `fk_depenses_has_users_depenses1`
    FOREIGN KEY (`id_depenses`)
    REFERENCES `appCompta`.`depenses` (`id_depenses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_depenses_has_users_users1`
    FOREIGN KEY (`id_users`)
    REFERENCES `appCompta`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
